databases:
  - name: File Uploads Primary
    databaseName: shrine_file_uploads
    user: shrine_file_uploads
    ipAllowList: []

services:
  - type: web
    name: File Uploads
    env: docker
    dockerfilePath: "./dockerfiles/webserver.Dockerfile"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: File Uploads Primary
          property: connectionString
      - key: LUCKY_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: APP_DOMAIN
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: SEND_GRID_KEY
        sync: false
